spring:
  application:
    name: cinema

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/cinema
    username: postgres
    password: 123

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration